spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: 123456

---
spring:
  config:
    activate:
      on-profile:
        - prod

  jpa:
    hibernate:
      ddl-auto: none

#  flyway:
#    table: flyway_schema_history
